apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-example-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-example-project
  template:
    metadata:
      labels:
        app: laravel-example-project
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}
      securityContext:
        fsGroup: 82
      containers:
        - name: fpm
          image: docker.io/riskidwiputra/php-apache:1.0.3
          resources:
            limits:
              cpu: 1000m
              memory: 1000M
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-example-project-service
spec:
  selector:
    app: laravel-example-project
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 80
  type: NodePort