apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_PASSWORD
              value: kanbaboard
            - name: MYSQL_ROOT_PASSWORD
              value: kanbaboard
            - name: SERVICE_TAGS
              value: dev
            - name: SERVICE_NAME
              value: mysql
            - name: MYSQL_DATABASE
              value: pengembangan_operasi
          resources: {}
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306