apiVersion: v1
kind: Service
metadata:
  name: laravel-example-project
  labels:
    app: laravel-example-project
spec:
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: laravel-example-project
